In [2]:
import numpy as np


In [63]:
#Нека за целта на операците потребителят зададе матрицата
rows = int(input("Number of rows:"))
cols = int(input("Number of cols:"))

matrixx = []
for i in range(rows):
    elements = []
    for j in range(cols):
        element = int(input("Vuvedi edin element"))
        elements.append(element)
    matrixx.append(elements)
matrix = np.array(matrix)

Number of rows: 2
Number of cols: 3
Vuvedi edin element 1
Vuvedi edin element 2
Vuvedi edin element 3
Vuvedi edin element 4
Vuvedi edin element 5
Vuvedi edin element 6


## Сега нека разгледаме основни операции с матрици

### достъп до някой елеменит в границите на матрицата

In [65]:
print(matrix[0][1])

2


## сумиране на eлементите в една матрица
### първо създаваме още една матрица:

In [67]:
rows = int(input("Number of rows:"))
cols = int(input("Number of cols:"))

matrixx2 = []
for i in range(rows):
    elements = []
    for j in range(cols):
        element = int(input("Vuvedi edin element"))
        elements.append(element)
    matrixx2.append(elements)
matrix2 = np.array(matrixx2)

Number of rows: 3
Number of cols: 4
Vuvedi edin element 5
Vuvedi edin element 6
Vuvedi edin element 7
Vuvedi edin element 8
Vuvedi edin element 3
Vuvedi edin element 1
Vuvedi edin element 4
Vuvedi edin element 6
Vuvedi edin element 8
Vuvedi edin element 3
Vuvedi edin element 6
Vuvedi edin element 2


In [69]:
print(matrix,matrix2)

[[1 2 3]
 [4 5 6]] [[5 6 7 8]
 [3 1 4 6]
 [8 3 6 2]]


### Сума от елемените на първата и втората матрица


In [71]:
#на първата
sum_elements_matrix = np.sum(matrix)
print(sum_elements_matrix)

#на втората
sum_elements_matrix2 = np.sum(matrix2)
print(sum_elements_matrix2)

21
59


## сума на матрици

In [80]:
## Конкатенация на две матрици, но да са с еднакви размери
m1 = np.array([[1,2,3],
             [2,3,4]])
m2 = np.array([[3,4,5],
              [4,6,7]])

new_matrix = m1+ m2
print(new_matrix)

[[ 4  6  8]
 [ 6  9 11]]


## Връщане на матрица към масив

In [87]:
flatten_matrix = m1.flatten()
print(matrix.flatten())
print(flatten_matrix)

[1 2 3 4 5 6]
[1 2 3 2 3 4]


## Умножение на матрици - резултатът е редове колкото първата и колони колкото втората матрица

In [90]:
print(np.dot(matrix,matrix2))

[[35 17 33 26]
 [83 47 84 74]]


## Умножение на матрици с еднакви размери

In [99]:
print(m1*m2)

[[ 3  8 15]
 [ 8 18 28]]


## Транспониране

In [107]:
transpose_matrix = np.transpose(matrix)
print(transpose_matrix)
print(matrix)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


## Намиране на дискриминанта - САМО НА КВАДРАТНИ МАТРИЦИ

In [116]:
## с помощта на  np.linalg.det(matrix)
m3 = np.array([[1, 2],
             [3,4]])
## знаем, че е ab - cd -> 4 - 6 = -2
det_m3 = np.linalg.det(m3);
print(int(det_m3))

-2


In [141]:
## по-сложен пример, също е по този начин
current_matrix = np.random.randint(0,10,(3,3));
det_current = np.linalg.det(current_matrix)
print(current_matrix)
print(int(det_current))

[[5 6 8]
 [0 5 3]
 [5 2 9]]
85


## Намиране на обратна матрица - само за матрици с положителна детерминанта и които са квадратни!!!

In [153]:
## с помощта на np.linalg.inv(matrix)

print(np.linalg.inv(m3))

[[-2.   1. ]
 [ 1.5 -0.5]]


## Добра практика е да правим нужните проверки, за да НЕ гърми!


In [177]:
##  например


def is_square(matrix):
    rows, cols = matrix.shape  # Получаваме размерите на матрицата
    return rows == cols

def has_positive_determinant(matrix):
  if is_square(matrix):
      det = np.linalg.det(matrix)
      return det > 0
  else :
     raise ValueError("Не е квадратна матрица")
      

In [185]:
if is_square(matrix):
    print("SQUARE")
else:
    print("NOT SQUARE")

NOT SQUARE


## Сума на диагоналите на матрица

#### Правим го с Trace()
#### dtype() - желан ретърн тип
#### offset() - отдалечаване от главния диагонал


In [189]:
#това ще отпечата по главния диагонал
print(np.trace(matrix, dtype=int))

6


In [203]:
# това печати с офсет
matrix_current = np.array([[1,2,3],[3,4,5],[7,8,9]])
print(np.trace(matrix_current, dtype=int))
print(np.trace(matrix_current, offset=1,dtype=int)) ## нагоре от главния
print(np.trace(matrix_current, offset=-1, dtype = int)) ## надолу от главния

14
7
11


## За умножение на многомерни матрици!! Използваме MATMUL(), а не DOT()


#### matmul() Arguments:
#### first_matrix - represents the first matrix we want to multiply
#### second_matrix - represents the second matrix we want to multiply
#### out (optional) - allows us to specify a matrix where the result will be stored

In [212]:
x = np.matmul(matrix,matrix2, out=None)
print(x)

[[ 35  17  33  26]
 [ 67  37  67  58]
 [131  77 135 122]]
