# Представяне на матрици


In [2]:
import numpy as np

In [10]:
matrix = np.array([[1,2,3],
                 [3,4,5],
                 [6,7,8]])


## Как да ги принтираме?

~два начина:

In [14]:
print(matrix)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


## Печатане на всички елеменити на матрицата

In [21]:
for row in matrix:
    for x in row:
        print(x)

1
2
3
3
4
5
6
7
8


In [39]:
for row in matrix:
    print(row)

[1 2 3]
[3 4 5]
[6 7 8]


In [41]:
for row in matrix:
    for element in row:
        print(element, end=" ")
    print()

1 2 3 
3 4 5 
6 7 8 


## Втори начин за зададени от потребителя матрици!

In [56]:
# създаваме празна матрица
matrix = []

# задават се брой редове и колони
matrix_rows = int(input("Моля въведи брой редове: "))
matrix_cols = int(input("Моля въведи брой колони: "))

# Въвеждаме елементите на всеки ред и ги добавяме към списъка
for i in range(matrix_rows):
    row = []  # Създаваме нов списък за текущия ред
    for j in range(matrix_cols):
        element = int(input(f"Въведи елемент за ред {i+1}, колона {j+1}: "))
        row.append(element)  # Добавяме елемента към текущия ред
    matrix.append(row)  # Добавяме целия ред към матрицата

final_matrix = np.array(matrix)
print(final_matrix);

Моля въведи брой редове:  2
Моля въведи брой колони:  3
Въведи елемент за ред 1, колона 1:  1
Въведи елемент за ред 1, колона 2:  2
Въведи елемент за ред 1, колона 3:  3
Въведи елемент за ред 2, колона 1:  4
Въведи елемент за ред 2, колона 2:  5
Въведи елемент за ред 2, колона 3:  6


[[1 2 3]
 [4 5 6]]


# Специални матрици от NumPy


## Единична матрица

In [67]:
# Задава се матрица 3х3, може да бъде и друго число,но положително
identity_matrix = np.eye(3)
print(identity_matrix)

## НЕВАЛИДНО 
##identity_matrix2 = np.eye(-1)
##print(identity_matrix2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Матрица,която е само с 1 или 0;

In [76]:
matrix_ones = np.ones((3,2));
print(matrix_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [80]:
matrix_zeros = np.zeros((3,4))
print(matrix_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Матрици, с random стойноси

In [93]:
matrix = np.random.rand(3,3) * 10;
print(matrix)

[[6.32157887 3.60535219 0.89036424]
 [9.23647435 0.35311116 7.06887288]
 [0.15996252 5.61836315 4.56076609]]


### Това е по-полезен начин, защото може да се задава и произволен интервал от стойности

In [98]:
matrix = np.random.randint(-1, 12,(3,2))
print(matrix)

[[ 0 -1]
 [11  3]
 [ 9  1]]
